# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 19:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Id_Number', models.CharField(max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,13}$')])),
                ('Street', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Postal_Code', models.CharField(max_length=50)),
                ('Cell_Number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
