# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 19:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqungu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Employee_Number',
            field=models.CharField(default=0, max_length=20, validators=[django.core.validators.RegexValidator('^\\d{1,20}$')]),
        ),
        migrations.AddField(
            model_name='client',
            name='Employer',
            field=models.CharField(default='sizo', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='Policy_type',
            field=models.CharField(choices=[('Investment', 'investment'), ('plan', 'plan'), ('funeral cover', 'funeral cover')], default='planing', max_length=99),
        ),
        migrations.AddField(
            model_name='client',
            name='Premium',
            field=models.DecimalField(decimal_places=2, default=66.0, max_digits=8),
        ),
    ]
