# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-17 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqungu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Policy_type',
            field=models.CharField(choices=[('Investment', 'investment'), ('retirement', 'retirement'), ('funeral cover', 'funeral cover')], default='', max_length=99),
        ),
    ]
