# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqungu', '0002_auto_20170725_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Employer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='Policy_type',
            field=models.CharField(choices=[('Investment', 'investment'), ('plan', 'plan'), ('funeral cover', 'funeral cover')], default='', max_length=99),
        ),
        migrations.AlterField(
            model_name='client',
            name='Premium',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
